version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm install
      - save_cache:
          key: npm-packagea 
          paths:
            - /src/node_modules
      - run: npm run lint

  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - restore_cache:
          keys: npm-packages 
      - run: npm install
      - run: npm run test

  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - chcekout
      - restore_cache:
          keys: npm-packages 
      - run: npm run audit

workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires: [build]
      - test:
          requires: [test]
